rcbops/rpc-upgrades

- pre_leap.sh
Remove the Horizon logo files vars from user_varables.yml
since they are now maintained in group_vars and represent
the outdated location of the logo files.
> RLM-216 Remove Horizon logo files variable

- tests/test-leapfrog.sh
Allows for setting specific series variables for the leapfrog script to set the target RPC branch and the desired OSA-OPs repo.
> Add series specific variable overrides for leapfrogging

- playbooks/patches/liberty/galera_server/galera_server_apt_repo_defaults.patch
- playbooks/patches/liberty/galera_server/galera_server_apt_repo_pre_install.patch
- run-tests.sh
- tests/aio-create.sh
- tests/run-tempest.sh
- tests/test-leapfrog.sh
Includes tempest tests, leaves disabled while we work through gate jobs.  Includes fix for RLM-328 to fix up percona repo that failed with bad signatures during initial provisioning, pins sshd role to commit before switching to the package module in Ansible 2.0 since we're using 1.9.
> Various Liberty fixes for initial deploy

- gating/pre_merge_test/run
- run-tests.sh
- tests/aio-create.sh
- tests/test-minor.sh
- tests/test-upgrade.sh
The current minor upgrade path simply involves running the newer version
of the deployment script, there is no specific upgrade code path to run.
This change introduces `tests/test-minor.sh` for running a minor upgrade
and `tests/test-upgrade.sh` for controlling which type of upgrade is
performed. If RE_JOB_UPGRADE_ACTION is either "leap" or "minor" the
appropriate script is executed.
`tests/aio-create.sh` is updated to support deploying a newton version
of the code as the base so that minor upgrades on the current release
can be tested.
> RE-913 Add support for minor upgrades

- scripts/ubuntu14-leapfrog.sh
Checks out the target branch directly to avoid any sort of submodule collisions by checking out master first.
> RLM-382 Checkout branch directly instead of master

- tests/test-leapfrog.sh
Runs maas-verify after leapfrog if /opt/rpc-maas exists.
Depends on https://github.com/rcbops/rpc-upgrades/pull/28
> RLM-306 Run maas-verify after leapfrog

- gating/pre_merge_test/run
- playbooks/ansible.cfg
- playbooks/maas-get.yml
- playbooks/maas-setup.yml
- tests/aio-create.sh
- tests/maas-install.sh
Deploys and verifies MaaS after deploy of AIO and before leapfrog.  
Uses playbooks in the repo copied from head rpc-openstack to checkout rpc-maas repo.  The older point releases of the various versions have the old maas release built in and is not using the rpc-maas repo.  Since the rpc-maas repo is our current preferred method, this runs and installs maas from there.
> RLM-305 Enable MaaS Deploy and Verify before Leap

- Vagrantfile
- run-tests.sh
- run_tests.sh
- testing.rst
* Removed old run_tests.sh symlink
* Updated run-tests.sh to call ./gating/pre_merge_test/pre and run
* Updated Vagrantfile with new RE_JOB_ACTION syntax and matrix
> [RLM-431] Update local testing to use gating vars

- scripts/ubuntu14-leapfrog.sh
Existing SHA seemed to go AWOL (https://github.com/openstack/openstack-ansible-ops/commit/aa050307aab3a044c7875c1e7f00368ccda812aa) so bumping to latest.
> RLM-511 Bump to latest OSA_OPS branch

- tests/test-leapfrog.sh
Corrects directory for maas-verify and allows for exit on error.
> RLM-526 Corrects running directory for maas-verify

- tests/aio-create.sh
Sets maas_swift_accesscheck_password on older
versions of liberty before deploying in order
for maas-setup to complete.
> RLM-518 Set maas_swift_accesscheck_password

- tests/test-leapfrog.sh
The last commit probably won't work as there's no ansible.cfg in that directory which prevents the inventory from being loaded.  This should allow for it to find it.
> RLM-526 Run from a directory with an ansible.cfg

- playbooks/elasticsearch-reindex.yml
- tests/aio-create.sh
- tests/test-leapfrog.sh
Uses the latest OA_OPS to pull in the containers_to_destroy work, doesn't upgrade ES on kilo, and fixes a playbook syntax issue in the reindex playbook.
> Use latest OA_OPS for ES and don't run on Kilo

- tests/aio-create.sh
By pulling recursive on the first run, it pulls all submodules (artifacts) and causes issues on checkouts of the branches.  Removes the recursive and updates submodules once the branch is changed.
> Prevent modules from getting pulled on first checkout

- gating/pre_merge_test/run
- playbooks/remove-old-agents-from-maas.yml
- scripts/post_leap.sh
- tests/aio-create.sh
- tests/maas-install.sh
- tests/test-leapfrog.sh
Restores playbook to remove old neutron container maas entries
which was removed in RLM-416.
Runs maas-install before and after leapfrog which gets rpc-maas
if it's not present, installs, and verifies.  It also handles
the jumping around of the maas_release variable and sets it to
master by default for now.
Also disables the Elastic Search Upgrade jobs on Kilo and Liberty.  The job currently works on L->N but not L-N-14.5 because the required rpc-o commit won't be in the release until 14.6.0.  It also is not currently supported on Kilo.  Leaving them disabled for now and we can reenable once 14.6.0 drops.
> RLM-554 Various MaaS fixes

- tests/aio-create.sh
Switches to ansible release with retries added
to alleviate random ssh timeouts that plague
leapfrog runs from passing occasionally.
> RLM-434 Implement Ansible Retries for older ver

- gating/pre_merge_test/run
- playbooks/qc-post-leap.yml
- scripts/post_leap.sh
- scripts/ubuntu14-leapfrog.sh
- tests/qc-test.sh
Create a post upgrade playbook to run support QC steps after the upgrade is
complete. This might be run automatically in the gates, but manually in 
customer upgrades.
> RLM-307 Add QC test in post-leap

- playbooks/maas-get.yml
- tests/maas-install.sh
rpc-deploy-playbooks will checkout rpc-maas even if the
deploy flag is off, so checking it out each pass here
ensures the version we want to deploy with is the one
from this file.
> RLM-653 Always attempt to check out the release

- playbooks/preflight-check.yml
Pre Ansible 2.1 requires httplib2 to be install for uri
module.
> RLM-735 Install httplib2 for uri check in preflight

- tests/create-mnaio.sh
Leapfrog pulls it down itself and expects in a certain
location
> MNAIO don't push openstack-ansible-ops to infra1

- tests/create-mnaio.sh
Ansible is purged at this point from infra1 so that it's forced
reinstalled with the ssh_retry repo.
> Purge openstack-ansible binary so kilo kicks off a bootstrap

- tests/create-mnaio.sh
Uses mirror.rackspace.com instead of archive.ubuntu.com due to reliability issues.  Dependent on https://review.openstack.org/#/c/527802/.
> RLM-842 Use mirror.rackspace.com for MNAIO

- tests/create-mnaio.sh
- tests/test-leapfrog.sh
Jenkins doesn't seem to be happy if the term is not set and tosses
a 'unknown': I need something more specific. when running leapfrog.
This attempts to get around that issue.
> RLM-900 Set the terminal before running Leapfrog

- tests/create-aio.sh
- tests/create-mnaio.sh
- tests/prepare-rpco.sh
Previously retries for AIO was not getting sourced any more
since breaking out prepare-rpco and create-aio.  This should
handle it better and cleans up the code a bit.
> RLM-899 Ensure ansible retries are getting ran for AIO and MNAIO

- tests/create-mnaio.sh
We don't want to use the old version during leapfrog
so we only source once during the deploy.
> Move Ansible Retries into their own variable file

- tests/create-mnaio.sh
All MNAIO jobs are passing now, so enable MaaS to see what remaining things break.
> Enables MNAIO MaaS now that MNAIO is more stable

- tests/maas-install.sh
Running verify after initial deploy in gating is redundant
and doesn't really buy us much if we're proceeding
with a leapfrog anyways and retesting afterwards.
> Verify MaaS only after leapfrog

- README.rst
- Vagrantfile
- gating/README.md
- scripts/ubuntu14-leapfrog.sh
- testing.rst
Now that r14.6.0 has been released and changed in the gate jobs, all
examples and the default version have been updated to r14.6.0
> RLM-1043 Update target version to r14.6.0

- tests/create-mnaio.sh
Was getting ssh connect timeouts during the first MaaS run.  This sets the Ansible retries for this run as well before Ansible is upgraded on the leapfrog.
> RLM-899 Add Ansible Retries for first MaaS run

- playbooks/preflight-check.yml
This pre-flight check will ensure all hosts and containers have adequate
storage available prior to running a leap upgrade. All hosts and
containers will be checked to see if they're greater than 97% full. If
any filesystem is reported as being too full the run will fail.
Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>
Issue: [RLM-317](https://rpc-openstack.atlassian.net/browse/RLM-317)
> [RLM-317] Add pre-flight check for FS usage

- playbooks/preflight-check.yml
- playbooks/scripts/required_user_config_keys.py
This preflight check will ensure the required configuration keys are
preent on in the system configuration files prior to allowing a
leap upgrade to run. Should any of the required keys are missing the
deployent will hault.
Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>
Issue: [RLM-269](https://rpc-openstack.atlassian.net/browse/RLM-269)
> [RLM-269] Add check for required configuration keys

- scripts/ubuntu14-leapfrog.sh
Prevents preflight from running on retries of the
leapfrog upgrade script.  This prevents errors from
attempting to run openstack-ansible against inventory
that might be crafted for a different version of
Ansible.
> RLM-1105 Ensure preflight runs once at the start

- scripts/ubuntu14-leapfrog.sh
Moves existing rpc-openstack to backup directory if
backup directory doesnt exist.  Checks out rpc-openstack
fresh if not present.  This allows rpc-upgrades to be the
only thing needed to checkout to an enviroment and will
pull the items that are needed.
> RLM-1118 Don't fail if rpc-openstack is not present

- tests/test-leapfrog.sh
Enables UPGRADE_ELASTICSEARCH in gates now that 14.6.0 contains the proper fixes.
> RLM-1128 Enables UPGRADE_ELASTICSEARCH in gates

- playbooks/glance-cache-cleanup.yml
- scripts/pre_leap.sh
- scripts/ubuntu14-leapfrog.sh
This action will wipe all glance image cache before leaping to prevent
the container too full to achieve upgrading.
> [RLM-712] Clean glance cache before leap

- scripts/pre_leap.sh
Existing code strips from user_rpcm_default_variables.yml so adding user_rpco_variables_overrides.yml too.
> RLM-271 Drop ansible_host from user_rpco_variables

- playbooks/patches/liberty/galera_server/galera_server_apt_repo_defaults.patch
Newer mariadb/galera versions require a xtrabackup of version 2.3.5
and higher to successfully SST databases.
> Bump xtrabackup version

- playbooks/patches/liberty/galera_server/galera_server_apt_repo_defaults.patch
The new xtrabackup requires libev4 but as we are
downloading and installing xtrabackup via dpkg, dependencies are
not resolved. The pre installation of libev4 before xtrabackup
will fix the missing dependency
> Adding libev4 for liberty xtrabackup patch

- playbooks/patches/liberty/galera_server/galera_server_apt_repo_defaults.patch
The installation of xtrabackup >2.2 is conflicting with the older
percona-xtrabackup-22 package and need to be removed if installed
> Remove percona-xtrabackup-22 conflict

- playbooks/roles/rpc_post_upgrade/defaults/main.yml
- playbooks/roles/rpc_post_upgrade/tasks/post-upgrade-utility.yml
- playbooks/roles/rpc_pre_upgrade/defaults/main.yml
- playbooks/roles/rpc_pre_upgrade/tasks/gather_stats.yml
Adding the insecure flag to the rpc_post and pre upgrade roles
for all openstack CLI commands.
Additionally the timestamp for backup_dir is stripped off colons
as it can break tools like tar
> Adding insecure flag when necessary

- playbooks/patches/liberty/galera_client/galera_client_remove_percona_xtrabackup.patch
- tests/prepare-rpco.sh
xtrabackup is only required for galera_server so
remove it if present in liberty in the
galera_client install.
> RLM-1234 Remove xtrabackup from galera_client

- playbooks/glance-cache-cleanup.yml
The glance cache clean was trying to do too much. This change simply
decends into the glance cache directory and removes all files found.
Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>
> [RLM-712] Clear the glance cache

- scripts/pre_leap.sh
ansible_ssh can be configured in any of the user yml
configuration files, which is mainly set below Newton releases
to roll out MAAS. As it breaks ansible 2.1 we need to remove it
from all occurences rather than just named files.
> RLM-271 Remove ansible_ssh from all user configs

- gating/pre_merge_test/run
- tests/create-mnaio.sh
Adds a flag for skipping upgrades in the event a tester wants to do the first part of the deploy but hold off on the remaining steps.
> Adds a flag for skipping UPGRADES, default is yes

- gating/pre_merge_test/run
- tests/create-mnaio.sh
- tests/upgrade-mnaio.sh
This commit pulls the MNAIO upgrade out of the
MNAIO create script and puts it into its own
script so that testers can call the upgrade at
a later time if needed
> Split MNAIO Upgrade from MNAIO Create Script

- gating/pre_merge_test/run
This commit replaces the Travis CI usage with jobs defined and run
within the standard rpc-gating Jenkins environment.  The environment
variable FUNCTIONAL_TEST is removed and instead we check if
RE_JOB_ACTION is not set to "tox-test" to determine if the functional
test should run.  Otherwise, we run tox w/ the specific environment
passed in via RE_JOB_SCENARIO.
NOTE: The .travis.yml file will be removed in a subsequent review.
> RE-1162 Replace Travis CI usage

- scripts/ubuntu14-leapfrog.sh
Assumes linked release in /opt/openstack-ansible is
the directory to bootstrap ansible from.
Since this will be linked to the current release
this should provide the version of Ansible we need to
complete upgrade.
> RLM-1146 Removes BOOTSTRAP_ANSIBLE_FOLDER variable

- playbooks/preflight-check.yml
Duplicate nova flavor exisiting would cause 'nova-manage db sync' failed
at the mirgration step. This check could prevent this case happened adn
let user have chance to cleanup db before leapupgrade.
> [RLM-273]Add duplicate flavor IDs check

- gating/pre_merge_test/post
E004: File did not end with a newline
> Fix bashate error

- tests/test-major.sh
Currently fires off the test-major.sh script for the major upgrade.
There are a few tweaks that will need to be done around the config
file migrations that will need to be done to get it fully working.
> RLM-1291 Adds hook in for major upgrades

- tests/prepare-rpco.sh
Older versions of kilo that use older setuptools fail
with install_requires must be a string  or list of strings
so use the latest version that will work.  Uses the version in
r11.1.9.
> RLM-1338 Set pin of setuptools if not set

- scripts/ubuntu14-leapfrog.sh
Purges Glance cache before preflight in order to prevent errors in
preflight from no space on glace nodes.
> RLM-1373 Purge Glance cache before preflight check

- scripts/pre_redeploy.sh
Isn't really used and ends up just stopping the process
waiting from user input.
> RLM-1388 Remove prompt to verify secrets

- tests/test-leapfrog.sh
- tests/test-upgrade.sh
Allows us to use statically named gate jobs for releases
so that we don't have to change the gate jobs monthly.
Looks for 14.RELEASE in the leap to part of the configuation
and if set, determines the latest r14. tag from RPC-O.
> RLM-1368 Use latest release tag for gate jobs

- playbooks/roles/rpc_pre_upgrade/tasks/gather_stats.yml
The rpc pre upgrade role was expecting neutron routers
to be installed and write out their status information.
As neutron routers are optional, the task to write the
status file is changed to default to an empty list
> Make Neutron routers optional

- scripts/pre_redeploy.sh
Increases apt cache timeout to 6 hours to ensure we're not
refreshing the cache everytime it's called during a maintenance
or deployment.
The default value is currently 600 seconds (10 minutes) upstream.
> RLM-1423 Increase apt cache timeout

- scripts/pre_redeploy.sh
OSA does many attempts to update apt during the deploy process
which can slow down the deployment on environments with high latency.
Using present should get us a similar result and reduce time for deployment.
Also sets haproxy_package_state to latest as the haproxy configuration file apparently requires newer versions of haproxy to load.
> RLM-1401 Set package_state to present instead of latest

- playbooks/preflight-check.yml
Depending on source version, some override files
may not be present before the upgrade.
The hard coded path is now replaced by a list of possible
configuration files
> Fix path selection for user_variables

- scripts/pre_redeploy.sh
RLM-1401 introduced a unwanted sideeffect that libvirt, qemu and
other packages did not get updated on the hosts, rendering nova-
compute broken.
Also the references inside pre_redploy using
user_osa_variables_defaults.yml are changed to use the
user_osa_variables_overrides.yml as the defaults file is managed by
OSA
> Revert RLM-1401 and correct osa overrides use

- playbooks/preflight-check.yml
Since insufficient space for rootfs backup would lead ugrade fail, this
check is added prior all the ugprade begin.
> [RLM-1371]Check space for rootfs backup

- playbooks/elasticsearch-reindex.yml
Force kills logstash if a graceful shutdown fails.  Gate jobs
were occasionally failing on trying to shutdown the service
so this attempts to shutdown gracefully before killing the
service.
> RLM-1437 Force kill logstash if graceful fails

- playbooks/preflight-check.yml
A check was added to remove existing
user_deleteme_post_upgrade_variables.yml configuration prior to
running the upgrade/redeploy stage
> Adding check for pre leap stale configs

- scripts/post_leap.sh
- scripts/pre_redeploy.sh
Since leapfrog is 100% API downitme, remove the throttle to
keep the APIs operational.
Also moves optimizations for improving leapfrog deploy speeds into
user_leapfrog_overrides.yml which is removed after a successful
leap since those values are mainly beneficial during the leapfrog.
> RLM-1340 Set serialization to 100%

- playbooks/patches/newton/rpc-o-14.7.0-ansible-role-requirements.patch
- scripts/pre_redeploy.sh
Injects the openstack_hosts fork on 14.7.0 which
includes the domain fixes for RLM-322.
> RLM-1438 Ensure we're using openstack_hosts fork

- playbooks/preflight-check.yml
Setting default string content to prevent with_items is not invalid.
> RLM-1446 Fix error when enable_lxc_fs_check is false

- playbooks/scripts/required_user_config_keys.py
The fix here is based on this[ SO answer](https://stackoverflow.com/questions/25108581/python-yaml-dump-bad-indentation?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).  I know that the ticket for this PR suggests quoting as the culprit, but logs and online discussion suggest some parsers just don't like the lack of indentation.  Even yamllint logs the lack of indentation as an error, even though PyYaml notes that indentation is explicitly optional in the YAML spec.
For Clarity:
```yaml
used_ips: #bueno
- 10.52.4.1,10.52.4.50
- 10.52.7.1,10.52.7.50
- 10.52.8.1,10.52.8.50
- 10.52.10.1,10.52.10.50
```
```yaml
used_ips: #no bueno
- 10.52.4.1,10.52.4.50
- 10.52.7.1,10.52.7.50
- 10.52.8.1,10.52.8.50
- 10.52.10.1,10.52.10.50
```
I tested this against the YAML files …
> RLM-1374 Indent Mapped Sequences

- tests/prepare-rpco.sh
In Tornado 5.0 versions of Python 2.7 that predate the ssl module update are no longer supported:
https://github.com/tornadoweb/tornado/blob/master/docs/releases/v5.0.0.rst
libvirt-python fails due to issues in 4.1.0
https://bugs.launchpad.net/openstack-requirements/+bug/1753539
Pinning these appears to get the kilo gates moving again.
> RLM-1367 Pin tornado and libvirt-python to fix kilo

- README.rst
- playbooks/preflight-check.yml
- scripts/ubuntu14-leapfrog.sh
Ideally users don't need worry about release upgrade from since
openstack-release can give the version. In fact at most of time it
cannot guarantee giving proper release info, especially the file not on
infra node or outdated. This check will force user to export correct
release name.
> RLM-1456 Force user to export release version

- README.rst
- Vagrantfile
- playbooks/patches/newton/rpc-o-14.11.0-resolv.conf.patch
- scripts/pre_redeploy.sh
- scripts/ubuntu14-leapfrog.sh
- testing.rst
Bumps rpc-upgrades to r14.11.0 and includes patch for
fixing resolv.conf issue RLM-1457.  The resolv.conf will be included in
in r14.12.0 but this lets r14.11.0 be usable now.
> RLM-1465 Bump rpc-upgrades to r14.11.0

- playbooks/scripts/required_user_config_keys.py
This ensures that the user config starts with `---`
The added ` explicit_end=False,` is added in hopes that it might address sightings of `---` in places other than the beginning of the document.
> RLM-1374  Malformed YAML 2: Electric Boogaloo

- tests/create-mnaio.sh
Install libvirt-dev for libvirt-python dependency to fix this error, should get MNAIO working for kilo as well.
```
11:11:52 Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from singledispatch->tornado==4.5.3->-r requirements.txt (line 14))
11:11:52 Building wheels for collected packages: libvirt-python
11:11:52   Running setup.py bdist_wheel for libvirt-python: started
11:11:53   Running setup.py bdist_wheel for libvirt-python: finished with status 'error'
11:11:53   Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Dz1SHk/libvirt-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d …
```
> Install libvirt-dev for libvirt-python dependency

- gating/pre_merge_test/collect_logs.yml
- gating/pre_merge_test/post
RPC-O gating scripts were updated to gather logs from
MNAIO and AIO builds.  This brings those scripts to
rpc-upgrades.  The previous iteration was pulled from
RPC-O as well.
> RLM-1470 Update gating post to leverage RPC-O scripts

- gating/pre_merge_test/pre
Previously Jenkins made sure that python-yaml was installed
on the host, but with the switch to using nodepool all
pre-requisites must be handled by the test itself.
> RE-1464 Install pre-requisite packages for MNAIO tests

- tests/run_system_tests.sh
This commit updates the path for the location of the dynamic inventory
file used by the system tests. This path brings it into compliance with
the `OSA_PATH` used by the installer.
> ASC-553 Fix path of inventory for system tests

- tests/prepare-rpco.sh
Pin cmd2 to pre 0.9.0.  Fixes kilo gates where os_heat fails on the newer cmd2.
> RLM-1492 Pin cmd2 to pre 0.9.0

- scripts/ubuntu14-leapfrog.sh
Adding a workaround when deployment host is not the same as a infra host
and the resulting issues around lookup/sync of the `/etc/openstack-release`
file
> Workaround for deployment host != infra host

- tests/create-mnaio.sh
In order to capture accurate metadata about Molecule system tests, the
"RPC_RELEASE" and "RPC_PRODUCT_RELEASE" environment variables need to be
stored in the "MNAIO_VAR_FILE". Values in this file are re-sourced by the
`run` script to ensure they are used by the system tests in reporting
their results.
> ASC-564 Persist release envvars for test results

- tests/create-mnaio.sh
This reverts commit 413428bb02e19e2e9bc85c355649144fe8acba5d.
Reverting this commit as it's breaking MNAIO gating as RPC_RELEASE is not defined (unbound variable). We'll need to probably rework this patch.
> Revert "ASC-564 Persist release envvars for test results"

- scripts/ubuntu16-newton-to-ocata.sh
This allows containers to be updated without hitting
the container inventory that hasn't been provisioned
yet in Ocata.
> Move apt update earlier before bootstrap of Ocata

- tests/prepare-rpco.sh
Uses a sed instead of a patch to avoid variations
across different versions.
> RO-4265 Simplify spice url patch

- playbooks/patches/mitaka/haproxy-symlink-fix.patch
- releasenotes/notes/add-mitaka-leapfrog-support-1b1cdfadb3ff53eb.yaml
- scripts/pre_redeploy.sh
- tests/create-mnaio.sh
- tests/prepare-rpco.sh
FLEEK-61 Adds Mitaka to Newton Support in rpc-upgrades
This commit enables support for running a Mitaka
upgrade and contains support needed for running
Mitaka AIO and MNAIO gating jobs.  It contains the
following fixes:
- Skips the variable migration for Mitaka
- Removes user_osa_variables_defaults as existing
settings don't work in Newton and adds neccessary
variables back into file.
- Disables Ceilometer in AIO, swift breaks because
it depends on Ceilometer running.
- Sets haproxy fix to run on AIOs only, not MNAIOs
Looks like Mitaka gate was hitting this as well, so
this ports the patch over to Mitaka.
- Pushes updated SPICE url to MNAIO infra1
- Ensures openstack_release is set to rpc_release to
avoid venv_tags from getting set to newton-eol instead
of the latest RPC release version. …
> FLEEK-61 Fixes for Mitaka Leapfrog

- tests/run_system_tests.sh
In order to capture accurate metadata about Molecule system tests, the
"RPC_RELEASE" and "RPC_PRODUCT_RELEASE" environment variables need to be
sourced. For upgrades these are not set by the CI jobs. This commit
ensures that they are created.
> ASC-564 Add release envvars for test results

- gating/check/run
This change fixes the RE_ENV file so that the environment variables
defined have values that are quoted. So for example without this fix,
`export RE_FOO_BAR=foo bar` is added to the file and when exported that
gives `RE_FOO_BAR=foo`. With this change it would become `export
RE_FOO_BAR='foo bar'` which gives `RE_FOO_BAR=foo bar`.
JIRA: RE-1685
> Fix creation of RE_ENV file

- tests/prepare-rpco.sh
Uses rcbops galera_server branch as we needed to bump
percona-xtrabackup version for testing the initial Mitaka
deploy.  Without this version bump, Galera hangs during
cluster installation.
> FLEEK-142 Use rcbops galera_server branch for Mitaka

- scripts/ubuntu16-newton-to-ocata.sh
- scripts/ubuntu16-ocata-to-pike.sh
- scripts/ubuntu16-pike-to-queens.sh
- scripts/upstream/ocata/run-upgrade.sh
- scripts/upstream/pike/run-upgrade.sh
- scripts/upstream/queens/run-upgrade.sh
Brings down the upstream scripts so that they can be modified
and optimized for leaping over Ocata to save some
deployment cycles
> Skips the ocata setup-openstack script during N->Q

- gating/check/post
- gating/check/post_send_junit_to_qtest.sh
This commit adds a script to upload molecule test result xml data to
qTest during the `post` stage of the gating pipeline.
> ASC-564 Send test results to qtest in post

- gating/generate_release_notes/generate_release_notes.sh
- gating/generate_release_notes/generate_reno_report.sh
This will ensure that release notes failures percolate up to where Jenkins logs will actually record something. Combined with https://github.com/rcbops/rpc-gating/pull/981 , we should start to get a better idea of where and when things fail.
The next step should be to also capture the "why" things fail.  At this point that'd require exporting reno_report.md.err to somewhere that Jenkins will actually reveal in logs.  But any quick solution feels brittle and hacky.  I don't want to add to that just yet.
> Ensure failed release notes jobs return nonzero exit code

- playbooks/preflight-check.yml
Runs a dpkg -a --configure; apt install -y -f to ensure all
package installs across all containers and hosts are clean so
the upgrade process isn't hindered by package failures from
apt being in a half completed state.
> FLEEK-155 Ensure apt is in a healthy state during preflight

- playbooks/preflight-check.yml
Previously if the flag was set to disable it would skip the
task to gather the data, but the following task would fail because
that data was missing.  This sets it to always gather that
information, tosses an informational alert and skips the hard failure.
> FLEEK-151 Fix enable_lxc_fs_check flag

- tests/create-aio.sh
- tests/create-mnaio.sh
Switches to using false for DEPLOY_MAAS to
ensure MAAS is not installed during the deployment
phase of gating job.
> RI-433 Ensure DEPLOY_MAAS is not ran

- gating/check/pre
MNAIO images use archive.ubuntu.com which is slow and fails
more often due to there being more hops to it. Instead we
prefer to use the Rackspace mirrors which are local to each
data centre and have turned out to be more reliable.
> Use rackspace mirror for apt sources

- releasenotes/notes/add-ansible-vault-support-6c64f901599431d4.yaml
- scripts/post_leap.sh
- scripts/pre_leap.sh
- tests/test-upgrade.sh
Adds support for decrypting secrets files during the leapfrog
process and reencrypting them at the end.
The process automatically removes the vault file.  To use,
ensure ANSIBLE_VAULT_PASSWORD_FILE is set to the location of the
Ansible Vault file.
> FLEEK-144 Add support for decryption of Vault files

- Vagrantfile
- playbooks/prepare-ocata-upgrade.yml
- scripts/ubuntu16-ocata-to-pike.sh
- scripts/ubuntu16-pike-to-queens.sh
- tests/create-mnaio.sh
- tests/maas-install.sh
- tests/prepare-rpco.sh
RI-435 Gating fixes and optimizations
* Installs ara package and callbacks on incremental upgrades, not
used for Newton and older because Ansible versions are too old.
This should let us start gathering metrics from upgrades from
Newton.
* Drops OSA_BRANCH variable since it's not used
* Add SERIES checks for newer releases to account for the releases
and give us a place for future modifications if needed.
* Only pushes updated spice-html5 url fixes if needed
* Set MNAIO guest OS based on RE_JOB_IMAGE_OS
* Clean out ansible roles on infra1 before deploy
* Correct RPC-O version checked out on queens upgrade
* Flip vagrant mitaka to leap from major
* Add logic for setting up MNAIO config files since source locations
change in RPC-O post Newton
* Disable skip install during O2P as migrations …
> WIP - RI-435 Gating fixes and optimizations

- gating/generate_release_notes/generate_reno_report.sh
Script pulled from rpc-o which includes fixes to allow gate to pass.
> Adjust generate_reno_report to handle tag failure

- gating/generate_release_notes/generate_reno_report.sh
- tests/create-aio.sh
- tests/create-mnaio.sh
- tests/maas-install.sh
- tests/test-leapfrog.sh
Both are unstable and break often from upstream
changes.  Disabling as they don't appear to provide a
lot of value in gate testing.
> Disable ELK install and MAAS verify in upgrades gating

- scripts/ubuntu16-pike-to-queens.sh
Old facts remain after the inventory has been updated.
This removes the facts and forces a rebuild of them the
next time a run happens.
> RI-466 Remove ansible_facts to clean old facts out

- tests/run-tempest.sh
Older versions are missing additional settings like disk format
which causes tempest to fail when uploading images to glance.
> Ensure tempest_images is not overridden

- tests/run-tempest.sh
Disable tempest volume backup for Queens testing to get test functioning.
> Disable tempest volume backup for Queens testing

- test-requirements.txt
Use minimum patch requests version that covers
CVE-2018-18074.
> Bumps requests in tests to >=2.20.0

- test-requirements.txt
With the version bump, don't need the exclusions anymore.
> Drop the older versions required

- gating/check/post
- gating/check/run
By setting a MNAIO upgrade job with the action of snapcap
it will skip the upgrade portion and capture the images of
the environment before the upgrade is ran if the deployment is
successful.  This way we can leverage the workarounds in
rpc-upgrades to deploy a snapshot state of older versions and
leverage those when testing upgrades.
> Adds the ability to capture images pre upgrade

- gating/check/post
Adds a check to load functions if available, so it doesn't
break on versions that don't have that file (older)
Also adds a check to run ARA if the binary is detected.  Older
versions did not support ARA, so if the binary isn't present, it
will skip ARA collection.
> Only run functions if available, run ARA log collection

- tests/test-upgrade.sh
When using snapshot builds, the head branches may
be out of date and can check out invalid code.
This refreshes the repo before upgrade to make sure
we're running the correct code.
> Ensure we always have the latest repo

- tests/prepare-rpco.sh
This removes the ceph roles from ansible-role-requirements
and updates the sshd role so that kilo deploys will work in
gating so that they can be upgrade tested.
> Prep role requirement for kilo upgrade tests

- Vagrantfile
- gating/check/run
- testing.rst
- tests/test-upgrade.sh
- tests/upgrade-mnaio.sh
In order to save space on gating job names, this shortens
incremental to inc.
Depends on https://github.com/rcbops/rpc-gating/pull/1228
> Shorten incremental action name

- incremental/incremental-upgrade.sh
- incremental/lib/functions.sh
- incremental/ubuntu16-upgrade-to-ocata.sh
- incremental/ubuntu16-upgrade-to-pike.sh
- incremental/ubuntu16-upgrade-to-queens.sh
- incremental/ubuntu16-upgrade-to-rocky.sh
This should prevent incremental upgrades from getting too far in out-of-date Ubuntu environments.
> [RI-596] Require Ubuntu 16 for incremental upgrades

- tests/create-mnaio.sh
Ensure user_mnaio_variables.yml isn't overwritten.  Also ensures user_variables isn't overwritten when copied from RPC-O.
> Ensure user_mnaio_variables.yml isn't overwritten

- incremental/playbooks/prepare-ocata-upgrade.yml
- incremental/ubuntu16-upgrade-to-ocata.sh
- incremental/ubuntu16-upgrade-to-pike.sh
Removes some tasks to symlink the secrets files and uses
the secrets function instead to set the secrets file to
the file that is present.
> Remove secrets relink and leverage the secrets variable

- tests/create-mnaio-snap.sh
Ensures the rpc-o repo on infra1 from the image snapshot
is overridden with a fresh repo that doesn't utilize ssh
repo.
> RI-630 Push rpc-openstack from host to infra1

- incremental/lib/functions.sh
- incremental/ubuntu16-upgrade-to-pike.sh
- incremental/ubuntu16-upgrade-to-queens.sh
- incremental/ubuntu16-upgrade-to-rocky.sh
Syncs group_vars and runs the site-release playbook
from rpc-openstack to ensure the proper variables for
a supported release are used during an upgrade.
This ensures the proper RPC release version numbers are set
and that any overrides we've made to the release are used
during the upgrade.
> Uses vars from rpc-openstack for upgrades

- incremental/lib/functions.sh
- incremental/playbooks/prepare-ocata-upgrade.yml
Also allows manual override by operator.
The reason for this is to avoid issues with failed reruns,
sometimes manifesting as template failures.  It also saves some
time on reruns.
> [RI-621] Only prep Ocata once at most

- README.rst
- Vagrantfile
- leapfrog.rst
- releasenotes/notes/2019-january-releases-d1bcc4d107352cdb.yaml
- scripts/ubuntu14-leapfrog.sh
- testing.rst
- tests/create-mnaio-snap.sh
This reverts commit 402d7195545142abe6b7b53d4d5bf8c9949f2c27.
r14.22.0 is an invalid release so reverting and will bump to a new tag past that.
> Revert "Bump to Newton r14.22.0 release"

- incremental/ubuntu16-upgrade-to-pike.sh
- incremental/ubuntu16-upgrade-to-queens.sh
To limit unexpected change, lock increments to
stable release branches of Pike and Queens.
> Sets released versions for RPC-O Pike/Queens

- gating/check/run
- tests/run-tempest.sh
- tests/upgrade-mnaio.sh
MNAIO and AIO should specify their own tempest
IPs to use, so drop the hardcode and see what jobs
can pass with this change.
> Enable tempest for all, drop tempest ips

- README.rst
- Vagrantfile
- leapfrog.rst
- releasenotes/notes/2019-january-releases-d1bcc4d107352cdb.yaml
- scripts/ubuntu14-leapfrog.sh
- testing.rst
- tests/create-mnaio-snap.sh
Bumps rpc-upgrades to use r14.23.0 for leapfrogs.
https://github.com/rcbops/rpc-openstack/tree/r14.23.0
> Bump Newton Leapfrogs to use r14.23.0

- incremental/lib/functions.sh
- incremental/ubuntu16-upgrade-to-ocata.sh
- incremental/ubuntu16-upgrade-to-pike.sh
- incremental/ubuntu16-upgrade-to-queens.sh
- incremental/ubuntu16-upgrade-to-rocky.sh
Ensures OSA bootstrap is ran to overwrite any RPC-O
specific bootstraps.  Writes a file to ensure it's
done at least once to flip things over so that we
always have OSA openstack-ansible available.
> Bootstrap OSA if it hasn't been done before

- tests/prepare-rpco.sh
When using an MNAIO, user_variables.yml for Mitaka is present but nothing is in it causing deploy.sh to fail.  This tosses a dummy var into it to prevent the failure.
> Populate user_variables.yml as it's empty

- playbooks/preflight-check.yml
apt_pinned_packages can break things during upgrades as
it overrides all pins in all roles.
This will fail if that variable is present prompting the user
to investigate and remove the setting if present.
> FLEEK-268 Check for apt_pinned_packages in overrides

- tests/create-mnaio.sh
A lot of older RPC playbooks are busted and we've moved a lot
of those components into external repos.  This removes
them during gate testing to reduce times and make tests more
stable.
> Disable RPC playbooks on MNAIO

- scripts/post_leap.sh
- scripts/pre_leap.sh
- tests/test-leapfrog.sh
The file `user_extras_secrets.yml` was forgotten to be decrypted during the upgrade, leading to corruption/destruction of the file/content
> User extras secrets fix

- tox.ini
Pin tests to working branch.  Newer commit to openstack-ansible-tests broke things, so we're pinning to last known working for now.
https://github.com/openstack/openstack-ansible-tests/commit/bb9d690eb09360fe03bf16bcfa0ffa2e2e8f5826
> Pin tests to working branch

- tests/prepare-rpco.sh
Kilo branches have ceph submodules built it,
so we purge them all after we check out so we
ensure osa is checked out without failure.
> Clean out kilo submodules of ceph

- playbooks/preflight-check.yml
During preflight, ensure ca-certificates package is
latest on hosts to avoid cert issues during leap.
> FLEEK-203 Ensure ca-certificates is latest

- incremental/lib/functions.sh
- incremental/playbooks/prepare-ocata-upgrade.yml
- incremental/playbooks/remove-rpco-repos.yml
Removes rpc-repo keys as they aren't used past Newton and prevents
apt update failures from expired keys.
> Remove rpc-repo GPG keys

- incremental/lib/functions.sh
- incremental/playbooks/prepare-queens-upgrade.yml
The playbook is used to execute task prior to the
queens upgrade
> Adding prepare-queens-upgrade.yml playbook

- tests/create-aio.sh
Due to various bitrot from things like horizon playbooks,
drop these from the install to simplify testing.  Most recent one is markdown breaking since it's not pinned in the horizon extensions repo:
```
2019-04-10T13:24:49-0500 TASK: [horizon_extensions | Install Horizon plugin] *************************** 
2019-04-10T13:25:02-0500 failed: [aio1_horizon_container-b8c6a4df] => {"changed": true, "cmd": ["python", "setup.py", "install"], "delta": "0:00:12.286921", "end": "2019-04-10 18:25:02.156632", "rc": 1, "start": "2019-04-10 18:24:49.869711", "warnings": []}
2019-04-10T13:25:02-0500 stderr: warning: no files found matching 'LICENSE'
2019-04-10T13:25:02-0500 zip_safe flag not set; analyzing archive contents...
2019-04-10T13:25:02-0500 rackspace.heat_store.views: module references …
```
> Disable AIO RPC playbook install

- incremental/playbooks/prepare-ocata-upgrade.yml
Patch has been submitted upstream to correct issue where killall wasn't
present and caused lxc-dnsmasq to not clean out existing
instances of dnsmasq.
Adding here temporarily to ensure it gets installed.  This should
negate the need for running the lxc-containers-restart.yml
that is used during the upgrade.
> Ensure psmisc is present

- scripts/post_leap.sh
- tests/create-mnaio-snap.sh
Previously leap tried to do additional items that have
now been broken out into other steps.  This removes
those steps from the leapfrog process.
> Remove maas and rpc-playbooks from post-leap

- incremental/lib/functions.sh
Depends on https://review.opendev.org/#/c/655199/ and backports to older releases.
> Write file to skip bootstrap-ansible on run-upgrade

- incremental/lib/functions.sh
The LXC containers are only rebuild once which
allows for restart of the upgrade.sh script
> Rebuild LXC containers only once

- incremental/lib/functions.sh
Ensures that openstack-release.upgrade reflects the completed
upgrade to avoid restarting from the original upgrade point.
> Ensure openstack-release.upgrade is updated

- README.rst
- incremental/incremental-upgrade.sh
- incremental/lib/functions.sh
- incremental/lib/vars.sh
- incremental/ubuntu16-upgrade-to-pike.sh
- incremental/ubuntu16-upgrade-to-queens.sh
- incremental/ubuntu16-upgrade-to-rocky.sh
- incremental/ubuntu18-upgrade-to-stein.sh
- incremental/ubuntu18-upgrade-to-train.sh
Adds initial support for upgrading to stein/train and treats rocky
as the upgrade point from Ubuntu 16.04 to 18.04 to test
with.  Anything being upgraded from 18.04 will make the
assumption that the rpc-config directory is required.
Rocky upgrades and up expect the rpc-config directory
to be present and setup (checks if /opt/rpc-config exists). If the /opt/rpc-config is not present, the upgrade will halt on stein/train upgrades.
> Adds initial support for upgrades to stein/train

- playbooks/roles/rpc_post_upgrade/tasks/post-upgrade-elasticsearch.yml
This pull request fixes the basic problems with this check.  However, the bigger issue is, for a lot or even almost all of our environments, the status for indices is probably always going to be yellow since we're running stand alone ES nodes.  @sdhardy ran into this during the Pipedrive upgrade.  It was easy enough to fix with something like:
```for i in $(curl -s localhost:9200/_cat/indices?v | awk '{print $3}'); do curl -s -XPUT localhost:9200/${i}/_settings -d '{"index":{"number_of_replicas":0}}'; done```
But I'm not sure we're doing anything like this elsewhere before this check, so I imagine this check will fail in a lot of our environments.
Either way, these changes here should still be made.
> Fix misspelling and incorrect syntax

- incremental/lib/functions.sh
- scripts/pre_redeploy.sh
The rsync tasks of the group vars is converted into a one-time
task to allow edits during upgrades without destroying these
upon restart
> Convert rsync tasks to one-time sync

- playbooks/roles/rpc_pre_upgrade/tasks/backup.yml
The backup task did not include a delegation to determine the backup
program location when galera is running inside containers.
This fix includes the missing delegation.
> Adding missing delegation for rpc_pre_upgrade role

- incremental/ubuntu18-upgrade-to-train.sh
- incremental/ubuntu18-upgrade-to-ussuri.sh
SKIP_CUSTOM_ENVD_CHECK is set to true when RPCO config templates
are present. This is generally the case since Stein
> Conditional setting of SKIP_CUSTOM_ENVD_CHECK
