rcbops/rpc-upgrades

README.rst, run-tests.sh, scripts/pre_redeploy.sh, scripts/ubuntu14-leapfrog.sh, testing.rst, tests/aio-create.sh, tox.ini
Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>
=> test end to end

scripts/ubuntu14-leapfrog.sh
Bumps to latest master for mariadb repo cleanup to fix galera client install issues.
=> RLM-263 Bump OA-OPS sha for mariadb repo cleanup

gating/post_merge_test, gating/pre_merge_test/post, gating/pre_merge_test/pre, gating/pre_merge_test/run, testing.rst, tests/aio-create.sh, tests/mnaio-create.sh, tests/test-leapfrog.sh, tox.ini
Add RE gating jobs for rpc-upgrades
=> Add RE gating jobs for rpc-upgrades

gating/pre_merge_test/run
Fixes a typo causing mnaio to not fire.
=> Fix typo on gating script

gating/README.md
Docs on how rpc-upgrades gating is set up.
=> RLM-277 Gating job documentation

Vagrantfile
=> RLM-355 Add Vagrantfile for Testing rpc-upgrades

tests/test-leapfrog.sh
This is breaking jobs so remove until fix can be tested and merged.
=> RLM-554 Comment out final maas-verify until fixed

playbooks/preflight-check.yml, scripts/pre_leap.sh, scripts/ubuntu14-leapfrog.sh
This script is designated to check if system meets requirement before
leaping. So it might be tempalte but it will be incremented with more
object to check, like security hardening. TBD.
=> RLM-294 Create preflight check for RPC upgrade

scripts/pre_leap.sh
Pins to the last known working version of python-ldap.
=> RLM-682 Pin python-ldap 2.5.2 for keystone

Vagrantfile
Bump Vagrantfile versions to 14.5.0.
=> RLM-636 Bump Vagrantfile to 14.5.0

scripts/post_leap.sh
Retrieves the latest MAAS tag during post leap, and sets the version before deploy-rpc-playbooks runs.  This ensures the latest MAAS version is set and prevents a revert to 1.0.0 as is set in 14.2.0 release.
=> RLM-274 Get latest MAAS tag and set as var

playbooks/maas-get.yml, tests/maas-install.sh
We want to avoid using the variable in the config files
for our test, so changes the variable to avoid running
into that.
=> RLM-653 Change the maas_release variable

gating/pre_merge_test/run, tests/ansible-env.rc, tests/create-aio.sh, tests/create-mnaio.sh, tests/prepare-rpco.sh, tests/test-upgrade.sh
Handles preparation of rpc-o and then runs appropriate job for aio or mnaio.
=> RLM284 Refactor Gating for MNAIO 

tests/create-mnaio.sh
ssh option to get rid of "unknown: I need something more specific"
error and push generated user_rpco_upgrade.yml to infra1
reference: https://superuser.com/questions/466102/ssh-returned-with-something-unknown
=> Tuning for MNAIO leapfrog to work

tests/create-mnaio.sh
Sets the terminal to help fix the 'unknown': I need something more specific error.
=> Set the terminal

tests/ansible-env.rc
Had the incorrect paths for the ansible plugins so they were not getting picked up correctly.
=> Set correct paths for ansible plugins

tests/ansible-env.rc
Removes setting of ansible variables to avoid issues when use multiple projects.
=> Reduce to ssh ansible values

tests/maas-install.sh
Pins to last know rpc-maas commit since it broke recently on kilo.
=> RLM-744 Pin to last known working rpc-maas commit

scripts/ubuntu14-leapfrog.sh, tests/test-leapfrog.sh
Should help fix Kilo issues around mariadb apt repos.
=> Use latest OA_OPS_REPO, have Kilo use it as well

scripts/ubuntu14-leapfrog.sh
Bumps target to r14.5.0 instead of r14.2.0.
=> RLM-816 Bump default target to r14.5.0

scripts/ubuntu14-leapfrog.sh
Brings in https://review.openstack.org/#/c/528048/
=> Bump to grab latest OA_OPS changes

gating/pre_merge_test/run, scripts/ubuntu14-leapfrog.sh
To ensure leapfrog is idempotent.
=> RLM-292 Add second leapfrog run to gating

testing.rst
Adds docs for testing an MNAIO leapfrog using gating scripts.
=> RLM-1088 Add docs for running tests on an MNAIO

tests/create-aio.sh, tests/create-mnaio.sh
Dumps the output of lsb_release -a and uname -a for quick reference.
=> RLM-1095 Display the current release and kernel

playbooks/roles/rpc_post_upgrade/README.rst, playbooks/roles/rpc_post_upgrade/defaults/main.yml, playbooks/roles/rpc_post_upgrade/tasks/main.yml, playbooks/roles/rpc_post_upgrade/tasks/post-upgrade-elasticsearch.yml, playbooks/roles/rpc_post_upgrade/tasks/post-upgrade-galera.yml, playbooks/roles/rpc_post_upgrade/tasks/post-upgrade-neutron-venv.yml, playbooks/roles/rpc_post_upgrade/tasks/post-upgrade-nova-venv.yml, playbooks/roles/rpc_post_upgrade/tasks/post-upgrade-rabbitmq.yml, playbooks/roles/rpc_post_upgrade/tasks/post-upgrade-swift-proxy.yml, playbooks/roles/rpc_post_upgrade/tasks/post-upgrade-utility.yml, playbooks/roles/rpc_post_upgrade/tasks/remove-holland.yml, playbooks/roles/rpc_post_upgrade/templates/neutron-port-status.txt.j2, playbooks/roles/rpc_post_upgrade/templates/neutron-router-status.txt.j2, playbooks/roles/rpc_pre_upgrade/defaults/main.yml, playbooks/roles/rpc_pre_upgrade/tasks/backup.yml, playbooks/roles/rpc_pre_upgrade/tasks/gather_stats.yml, playbooks/roles/rpc_pre_upgrade/tasks/gather_swift_stats.yml, playbooks/roles/rpc_pre_upgrade/tasks/log_rotation.yml, playbooks/roles/rpc_pre_upgrade/tasks/main.yml, playbooks/roles/rpc_pre_upgrade/templates/instance-volume-mappings.txt.j2, playbooks/roles/rpc_pre_upgrade/templates/running-instances.txt.j2, playbooks/roles/rpc_pre_upgrade/templates/status.txt.j2, playbooks/roles/rpc_pre_upgrade/templates/swift_recon.txt.j2, playbooks/rpc-post-upgrades.yml, playbooks/rpc-pre-upgrades.yml
Moves rpc_pre_upgrade and rpc_post_upgrade roles out
of RPC-O newton into rpc-ugprades
=> RLM-1129 Move rpc_*_upgrade roles out of RPC-O

scripts/ubuntu14-leapfrog.sh
=> Adding marker file for glance-cache-cleanup.yml

scripts/ubuntu14-leapfrog.sh
Bump for recent fixes to leap upgrades.
=> Bump OA_OPS repo SHA

scripts/pre_redeploy.sh
Prevents it from running multiple times on
additional retries
=> RLM-1223 Add a marker for configure-apt-sources

tests/prepare-rpco.sh
Adds maas_swift_accesscheck_password to prepare-rpco
script for kilo
=> RLM-1318 Add maas variable to kilo

tests/test-major.sh
Adds a few tweaks to get Mitaka to Newton to roll.
=> RLM-1291 Add some fixes for Mitaka to Newton

tests/test-major.sh
Upgrade script fails with 'unknown': I need something more specific.  Set term to get around this.
=> RLM-1291 Set term to avoid unknown error

tests/prepare-rpco.sh
Overwrote the file by mistake when meaning to append to it.
=> RLM-1338 Append the requirements file instead of overwrite

README.rst, Vagrantfile, scripts/ubuntu14-leapfrog.sh, testing.rst
=> RLM-1339 Bump rpc-upgrades to 14.7.0 release

scripts/pre_leap.sh
Skips V-38462 and V-38660 (SNMPv2)
=> RLM-1375 Skip Security Hardening Checks

scripts/pre_redeploy.sh
Add 'openstack_domain' value setting into pre_redeploy.
=> [RLM-322]Set 'openstack_domain' value

scripts/ubuntu14-leapfrog.sh
Bump to latest sha to include skip tags on security hardening: https://github.com/openstack/openstack-ansible-ops/commit/007371b35c46170bc7eb47a17b101c6ea7ca0c84
=> Bump to latest OSA_OPS sha

playbooks/preflight-check.yml
=> [RLM-319] Ensure Glance Auth v2 for Cloudfiles

scripts/ubuntu14-leapfrog.sh
Uses loose artifacts during the newton leapfrog
upgrade process.
=> RLM-1408 Use loose artifacts on newton upgrades

gating/generate_release_notes/generate_release_notes.sh, gating/generate_release_notes/generate_reno_report.sh, gating/generate_release_notes/release_notes_dockerfile, gating/generate_release_notes/run, releasenotes/config.yaml, releasenotes/source/conf.py
Adds gating scripts for generating release notes.
=> RLM-1424 Add generate_release_notes gating

playbooks/roles/rpc_pre_upgrade/tasks/enable_maas_holland.yml, playbooks/roles/rpc_pre_upgrade/tasks/main.yml
PR 135 passed gating but included several syntax issues which are addressed with this fix
=> Fix syntax and logic issues around enable_maas_holland.yml

playbooks/preflight-check.yml
Make preflight check having ability to determine if NFS mount exists. If
so advanced glance config is needed to perform.
=> RLM-1372 Add NFS mount check

scripts/pre_redeploy.sh
Original path lacks of 'playbook'.
=> Fix rpc-14.7 patch path

scripts/pre_redeploy.sh
The live patching of the r14.7.0 ansible role broke idempotency.
A check is added to skip patching when successful
Closes-Bug: RLM-1451
=> Fix r14.7.0 role patch idempotency

README.rst, Vagrantfile, scripts/ubuntu14-leapfrog.sh, testing.rst
=> RLM-1450 Advance to r14.10.0

README.rst, Vagrantfile, scripts/ubuntu14-leapfrog.sh, testing.rst
Bump rpc-upgrades to use r14.12.0 on leap
=> RLM-1469 Bump rpc-upgrades to use r14.12.0 on leap

gating/pre_merge_test/run, tests/create-mnaio.sh, tests/run_system_tests.sh
This commit adds the execution of
[rpc-openstack-system-tests](https://github.com/rcbops/rpc-openstack-system-tests)
and uses an additional field on the `RE_JOB_ACTION` parameter to trigger
them.
=> ASC-476 Add system testing

README.rst, Vagrantfile, scripts/ubuntu14-leapfrog.sh, scripts/ubuntu14-mitaka-to-newton.sh, testing.rst
Bump rpc-upgrades for RPC-O r14.13.0
=> Bump rpc-upgrades for RPC-O r14.13.0

doc/source/conf.py, doc/source/index.rst, doc/source/releasenotes/index.rst, releasenotes/config.yaml, releasenotes/notes/version-test-6322a10bb3dd582b.yaml
Like the title says, this is just a basic setup.
=> Get basic sphinx and reno setup working

Vagrantfile, playbooks/files/etc-apt-apt.conf.d-local, playbooks/mnaio-trusty-to-xenial.yml, scripts/ubuntu16-newton-to-ocata.sh, scripts/ubuntu16-ocata-to-pike.sh, scripts/ubuntu16-pike-to-queens.sh, tests/test-incremental.sh, tests/test-upgrade.sh, tests/upgrade-mnaio.sh
Add scripts for testing incremental OSA major upgrades.  Tests from Newton to Queens on an AIO running 16.04 currently.
=> RLM-1471 Add scripts for testing incremental OSA major upgrades

releasenotes/releasenotes/notes/incremental-upgrades-761269d6ab27ae9f.yaml, scripts/ubuntu16-newton-to-ocata.sh, scripts/ubuntu16-ocata-to-pike.sh, scripts/ubuntu16-pike-to-queens.sh
Also uses the stable branch name for checkout of OSA
=> RLM-1471 Upgrade packages before upgrade

playbooks/prepare-ocata-upgrade.j2, playbooks/prepare-ocata-upgrade.yml, scripts/ubuntu16-newton-to-ocata.sh
Adds playbook for prepping incremental upgrades, fixes up
repos, brings all packages to latest, fixes up configs before
running upgrades.
=> RLM-1471 Adds playbook for prepping incrementals

playbooks/patches/kilo/spice-html5-repo-fix.patch, tests/create-mnaio.sh, tests/prepare-rpco.sh
Sets OSA_REPO if series is newton.
Depends on https://review.openstack.org/#/c/573455/
Also inject updated spice repo on pre newton
=> RO-4265 Use rcbops OSA if series is newton

README.rst, Vagrantfile, scripts/ubuntu14-leapfrog.sh, scripts/ubuntu14-mitaka-to-newton.sh, testing.rst
Bump rpc-upgrades to use r14.14.0
=> RLM-1497 Bump rpc-upgrades to use r14.14.0

playbooks/patches/liberty/spice-html5-repo-fix.patch, tests/prepare-rpco.sh
Add Spice patch for Liberty as well
=> RO-4265 Add Spice patch for Liberty as well

playbooks/prepare-ocata-upgrade.yml
Upgrade all containers to latest during N->O
=> Upgrade all containers to latest during N->O

scripts/ubuntu14-leapfrog.sh
Includes bump to newton-eol and Mitaka upstream additions
=> FLEEK-80 Bump OA_OPS for latest upstream fixes

README.rst
=> Update readme for Mitaka leap

tests/prepare-rpco.sh
FLEEK-84 Various fixes for deploying older Mitaka
* Patch in horizon install branch in Mitaka
* Uses mitaka-eol galera_server which contains fixes for install
* Ensures galera/rabbit are only deployed with a single affinity
=> FLEEK-84 Various fixes for deploying older Mitaka

tests/prepare-rpco.sh
Adds maas_swift_accesscheck_password used during maas install
=> FLEEK-12 Add maas_tweaks to Mitaka

scripts/pre_leap.sh
Uses older setuptools if bad version found
=> FLEEK-125 Use older setuptools for Mitaka installs

scripts/pre_leap.sh
Adds osa_secrets_file_name config option if
file is present and option is not set in
user_osa_variables_defaults.yml
=> FLEEK-124 Add osa_secrets_file_name config option

scripts/pre_leap.sh
=> FLEEK-125 Fix syntax error

README.rst, Vagrantfile, scripts/ubuntu14-leapfrog.sh, scripts/ubuntu14-mitaka-to-newton.sh, testing.rst
=> FLEEK-132 Bump rpc-upgrades to r14.15.0

tests/prepare-rpco.sh
Moves reset default apt sources to after installing libvirt-dev.  Fixes kilo issue on MNAIO.
=> Reset default apt sources after installing libvirt-dev

scripts/ubuntu14-leapfrog.sh
Brings in https://review.openstack.org/#/c/580670/
to fix race condition on setuptools 34.x
=> FLEEK-125 - Bump OA_OPS to latest

scripts/ubuntu14-leapfrog.sh
Existing check was not picking up correctly and not setting
variables correctly.
=> Fix non working check for CODE_UPGRADE_FROM

scripts/ubuntu16-newton-to-ocata.sh, scripts/ubuntu16-ocata-to-pike.sh
Aside from some unrelated apt-cache issues, this seems to play nicely.  I figure this needs more work, but I wanted to hit it with gating and get more eyes on it.
=> RI-348 Skip Ocata, and minimize Pike install for N2Q

README.rst, releasenotes/notes/skip-incremental-installs-7cf47561028d1a0b.yaml, scripts/ubuntu16-ocata-to-pike.sh
Small tweaks to make skipping ocata and pike install more consistent and documented.
=> RI-348 Revise and Document N2Q Incremental Skipping

scripts/ubuntu14-leapfrog.sh
Includes swift skip and corrects bind mount issues
=> FLEEK-167 Bump OA_OPS to latest

scripts/pre_leap.sh, tests/create-aio.sh
Has been dropped from the upgrade process, so this removes
some cruft.
=> FLEEK-152 Remove security hardening from process

README.rst
=> FLEEK-168 Add docs for skipping swift

releasenotes/notes/various-upgrade-improvements-b36b58b2cd171268.yaml
Add release notes for recent fixes
=> Add release notes for recent fixes

tests/test-leapfrog.sh, tests/test-upgrade.sh
Will circle back and add support for incremental upgrades
=> Disable vault encrypt for incremental

scripts/run-upgrade/queens/run-upgrade.sh, scripts/ubuntu16-pike-to-queens.sh
Current queens script doesn't exit properly so adding
in the fix here to test queens in gate.
=> Testing fix for queens upgrades, using local fork

README.rst, Vagrantfile, releasenotes/notes/2018-september-releases-6c4472aaa4f47828.yaml, scripts/ubuntu14-leapfrog.sh, scripts/ubuntu14-mitaka-to-newton.sh, scripts/ubuntu16-ocata-to-pike.sh, scripts/ubuntu16-pike-to-queens.sh, testing.rst, tests/maas-install.sh
Bump RPC-O and MaaS to Sept 2018 releases
=> FLEEK-180 Bump RPC-O and MaaS to Sept 2018 releases

tests/create-mnaio.sh
See https://review.openstack.org/#/c/600875/
=> Remove cleanup now that bootstrap is not run

gating/check/run
Disable MaaS runs on incrementals
=> Disable MaaS runs on incrementals

tests/create-mnaio.sh
DATA_DISK_DEVICE is no longer present so use new method
=> Update MNAIO disk to use

tests/create-mnaio.sh
Sets default_vm_disk_mode=file and lets mnaio determine available
space.
=> Use file mode and let script find available space

scripts/ubuntu16-ocata-to-pike.sh, scripts/ubuntu16-pike-to-queens.sh
Also removes repo_server fixes since it merged upstream
=> Add keystone hack for ocata until merges

README.rst, Vagrantfile, releasenotes/notes/2018-october-releases-0f0cc949a1bdbb0c.yaml, scripts/ubuntu14-leapfrog.sh, scripts/ubuntu14-mitaka-to-newton.sh, scripts/ubuntu16-pike-to-queens.sh, testing.rst
=> Add October 2018 releases

gating/check/pre, tests/prepare-rpco.sh
Pin to specific get-pip to avoid instabilities upstream
=> Pin to specific get-pip to avoid instabilities upstream

gating/check/pre, gating/check/run, gating/gating_prerequisites.sh, gating/gating_vars.sh, gating/mnaio_vars.sh, tests/create-mnaio-snap.sh, tests/create-mnaio.sh
Gating refactor
Clean up, support for snapshot builds
=> Gating refactor

scripts/ubuntu16-ocata-to-pike.sh
Disable pike hacks to see if Ocata can resolve.
=> Disable pike hacks

scripts/ubuntu16-newton-to-ocata.sh
=> Skip Ocata during N2Q

incremental/incremental-upgrade.sh
Prevent direct upgrade to Ocata, remove dup code
=> Prevent direct upgrade to Ocata, remove dup code

README.rst, incremental/incremental-upgrade.sh, incremental/lib/functions.sh, incremental/lib/vars.sh, incremental/ubuntu16-upgrade-to-ocata.sh, incremental/ubuntu16-upgrade-to-pike.sh, releasenotes/notes/incremental-upgrades-redux-4c99196dea504f4f.yaml, tests/test-incremental.sh
Fixes links in README
Drops Keystone Memcache Hack and relies on upstream fixes
Sets keystone_flush_memcache to yes during upgrade
Adds relnotes about incremental upgrades
=> Incremental Upgrades updates

gating/check/post
Adjust vars for artifact upload
=> Get version of job context for artifact upload

tests/create-mnaio-snap.sh
Checks for RPCU location first and then attempts to check
RPC-O repo for images to use as a snapshot.
=> Add RPCU artifact URL

gating/check/run
Set RE_JOB_BRANCH to master if not defined
=> Set RE_JOB_BRANCH to master if not defined

README.rst, Vagrantfile, leapfrog.rst, releasenotes/notes/2018-december-e290b66ba2ed9f85.yaml, scripts/ubuntu14-leapfrog.sh, testing.rst, tests/create-mnaio-snap.sh
Bump rpc-upgrades leapfrog to use RPC-O r14.20.0
=> Bump rpc-upgrades leapfrog to use RPC-O r14.20.0

tests/create-mnaio.sh
The style of deploy changes post newton, so we adjust
the create-mnaio script to account for the variations
in deployment.
=> RI-467 Uses a case to handle deploys for diff vers

incremental/lib/functions.sh, incremental/ubuntu16-upgrade-to-pike.sh, incremental/ubuntu16-upgrade-to-queens.sh, incremental/ubuntu16-upgrade-to-rocky.sh
This reverts commit df84bb2933a3ae5fa58645fea88553ff2385a3fc.
=> RI-606 Revert "Uses vars from rpc-openstack for upgrades"

incremental/lib/functions.sh
Adds callback location for ARA to capture logs
=> Add ARA for callbacks

gating/check/collect_logs.yml, gating/check/post
Generates and retrieves ARA logs if ARA binary is present and drops them into artifact directory.
=> RI-542 Generate and retrieve ARA logs

playbooks/roles/rpc_pre_upgrade/tasks/backup.yml
Remove  Copy xtrabackup task due to FLEEK-252 and offload that into the Shift Ops Maintenance plan
=> Remove Copy xtrabackup task due to FLEEK-252

incremental/lib/functions.sh, incremental/playbooks/prepare-ocata-upgrade.yml
Because we're removing some apt sources and changing them,
do a apt refresh cache at this point to avoid package install
issues later
=> Remove some redundant plays and refresh apt cache

incremental/lib/functions.sh, incremental/playbooks/create-cell0.yml, incremental/playbooks/db-migration-ocata.yml, incremental/playbooks/prepare-ocata-upgrade.yml
Adds Cells v2 DB
Adds initial Cells v2 cells
Does Cinder/Nova migration from Ocata venv
Removes deletion of openstack-ansible wrapper in Ocata prepare as
it should be overwritten during the next bootstap
=> FLEEK-243 Adds Ocata Cell Generation and Nova/Cinder migrations

incremental/playbooks/db-migration-ocata.yml
Adds online_data_migrations for Nova/Cinder and maps cell1 instances.
=> Adds online_data_migrations for Nova/Cinder, maps cell1

incremental/incremental-upgrade.sh, incremental/lib/functions.sh, incremental/playbooks/rpco-upgrade-configs.yml, incremental/ubuntu16-upgrade-to-ocata.sh, incremental/ubuntu16-upgrade-to-pike.sh, incremental/ubuntu16-upgrade-to-queens.sh, incremental/ubuntu16-upgrade-to-rocky.sh
Generates the user_rpco_upgrade.yml file used for the
upgrade process.  It includes variables needed for
optimation of the upgrade process and any particular
config values that might be necessary during the upgrade.
Upon completion of the upgrade, the file is removed and no
longer needed.
=> Adds an Ansible playbook for user_rpco_upgrade.yml

tests/create-mnaio-snap.sh
Adjusts vars around, to retrieve the snapshot images, add the latest queens and rocky snap urls.
=> Tuning create-mnaio-snap to actually work

incremental/lib/functions.sh, incremental/playbooks/configure-lxc-backend.yml
Various Incremental Upgrade Fixes
- Cleans repo container before upgrade to reduce space
- Configures lxc_container_backing_store
- Runs osa bootstrap to ensure osa bootstrap is in a clean state,
hopefully removes no module named osa_toolkit errors
=> Various Incremental Upgrade Fixes

tests/prepare-rpco.sh
Adds some missing MNAIO settings to lay down Kilo
so that we can test from a snapshot.
=> Add settings to get mnaio to work for K2N tests

scripts/ubuntu14-leapfrog.sh
Brings in:
Skip neutron rebalance if ha-tool is disabled
https://review.opendev.org/#/c/652205/
=> Use latest leapfrog changes:

incremental/lib/functions.sh
In the cases rpc-o isn't present, check it out
=> Checkout rpc-o if it's not present

incremental/lib/functions.sh, incremental/playbooks/prepare-rocky-upgrade.yml, tox.ini
Clears out apt proxies and corrects working directory for
existing queens prep.
=> Add Rocky prep to incremental

scripts/ubuntu14-leapfrog.sh
Fixes https://github.com/rcbops/rpc-upgrades/issues/368
https://github.com/rcbops/rpc-openstack/tree/r14.23.1
https://github.com/rcbops/openstack-ansible-openstack_hosts/pull/4
=> Uses r14.23.1 branch to include hosts fixes

incremental/lib/functions.sh
=> Fix ensure_working_dir

incremental/incremental-upgrade.sh, playbooks/roles/rpc_pre_upgrade/tasks/backup.yml, playbooks/roles/rpc_pre_upgrade/tasks/enable_maas_holland.yml
- Adding support for mariabackup
- Adding user_local_variables.yml files to role
=> Fixing rpc_pre_upgrade for Stein upgrades

incremental/incremental-upgrade.sh, incremental/lib/functions.sh, incremental/playbooks/variable-migrations.yml
The playbook `variable-migrations.yml` will migrate known changes or
issues around OSA variables prior to running the upgrade
=> Adding variable-migrations.yml

incremental/lib/functions.sh, incremental/ubuntu18-upgrade-to-victoria.sh
RPCOS-91 #time 30min Total work logged #comment adding stub code for upgrades
=> Adding stub code for Ussuri to Victoria Upgrade

incremental/playbooks/prepare-wallaby-upgrade.yml, incremental/playbooks/vars/wallaby.yml
Add overrides to pull git sources from github rather then opendev  to throttling
=> Add overrides to pull git sources from github
